# Generated by Django 2.1.7 on 2019-03-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Empty', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(default='Add text here..', max_length=300),
        ),
    ]
